[package]
name = "crittester"
version = "1.0.1"
edition = "2021"

[profile.release]
strip="debuginfo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
